repos:
-   repo: local
    hooks:    
    -   id: unit-tests
        name: Rodando testes unit√°rios
        language: system
        pass_filenames: false  
        entry: pipenv run python manage.py test words.tests.test_serializers && pipenv run python manage.py test words.tests.test_viewsets && pipenv run python manage.py test words.tests.test_models